### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by RadTechDad** [LEv145/--sd-webui-ar-plus#17]
Can i propose that you rename the repo to just `sd-webui-ar-plus` instead of `--sd-webui-ar-plus`?

This causes filesystem issues when trying to access the files in a command line.

For example, when trying to move the folder `mv --sd-webui-ar-plus`, it sates ,`mv: illegal option -- -` because it thinks the folder name is a passed argument.

**Comment by LEv145** [comment]
These special characters are needed so that auto1111 shows the extension on top of the others

Other extensions use the special character `-` and there are no problems accessing them
![изображение](https://github.com/LEv145/--sd-webui-ar-plus/assets/40071054/248490c2-0752-4a52-b1e0-6cb57beaa82c)

Try ` mv -- --sd-webui-ar-plus meow`

**Comment by RadTechDad** [comment]
using a `-` or `--` is fine, so long as it's not at the beginning of the folder name. Also, other aspect ratio extensions are able to be at the top of the list without the `--` at the beginning of their folder names.

**Comment by LEv145** [comment]
If the extension starts with "a", then of course it will be at the top
Yes, and I don't see any problems accessing the directory like this: `./--sd-webui-ar-plus`
